import java.util.HashMap;
import java.util.Map;

public class ServerString {

   static final ServerString aClass482_8765 = new ServerString("You are not currently in a channel.", "Du befindest dich derzeit nicht in einem Chatraum.", "Vous n\'êtes dans aucun canal à l\'heure actuelle.", "No momento você não está em um canal.", "En este momento no estás en un canal.");
   static final ServerString aClass482_8766 = new ServerString("Select", "Auswählen", "Sélectionner", "Selecionar", "Seleccionar");
   public static final ServerString aClass482_8767 = new ServerString("Unknown developer command: ", "Unbekannter Befehl: ", "Commande inconnue : ", "Comando desconhecido: ", "Comando desconocido: ");
   static final ServerString aClass482_8768 = new ServerString("Your friends chat channel has now been disabled!", "Dein Freundes-Chat ist jetzt ausgeschaltet.", "Votre canal de discussion est maintenant désactivé !", "O seu bate-papo entre amigos foi desativado!", "¡Tu canal de chat entre amigos ha sido desactivado!");
   static final ServerString aClass482_8769 = new ServerString("#Player", "#Spieler", "#Joueur", "#Jogador", "#Jugador");
   static final ServerString loginToMembers = new ServerString("Login to a members\' server to use this object.", "Du musst auf einer Mitglieder-Welt sein, um diesen Gegenstand zu benutzen.", "Connectez-vous à un serveur d\'abonnés pour utiliser cet objet.", "Acesse um servidor para membros para usar este objeto.", "Accede a un servidor para miembros para usar este objeto.");
   static final ServerString aClass482_8771 = new ServerString("Swap this note at any bank for the equivalent item.", "Dieses Zertifikat kann in einer Bank entsprechend eingetauscht werden.", "Échangez ce reçu contre l\'objet correspondant dans la banque de votre choix.", "Vá a qualquer banco para trocar esta nota pelo objeto equivalente.", "Cambia este vale en cualquier banco por el objeto equivalente.");
   static final ServerString aClass482_8772 = new ServerString((String)null, "geschickt werden.", (String)null, (String)null, (String)null);
   public static final ServerString discardStr = new ServerString("Discard", "Ablegen", "Jeter", "Descartar", "Descartar");
   public static final ServerString aClass482_8774 = new ServerString("wave:", "welle:", "ondulation:", "onda:", "onda:");
   public static final ServerString aClass482_8775 = new ServerString("Self", "Mich", "Moi", "Eu", "Mí");
   static final ServerString aClass482_8776 = new ServerString("You are not currently in a friends chat channel.", "Du befindest dich derzeit nicht in einem Freundes-Chatraum.", "Vous ne faites pas partie d\'un canal de discussion.", "No momento, você não está no bate-papo entre amigos.", "Actualmente no estás en un canal de chat entre amigos.");
   static final ServerString aClass482_8777 = new ServerString((String)null, "indem du dich ins Spiel einloggst.", (String)null, (String)null, (String)null);
   public static final ServerString aClass482_8778 = new ServerString("white:", "weiss:", "blanc:", "branco:", "blanco:");
   static final ServerString aClass482_8779 = new ServerString("Invalid player name.", "Unzulässiger Charaktername!", "Nom de joueur incorrect.", "Nome de jogador inválido.", "Nombre de jugador no válido.");
   static final ServerString aClass482_8780 = new ServerString("You can\'t report yourself!", "Du kannst dich nicht selbst melden!", "Vous ne pouvez pas vous signaler vous-même !", "Você não pode denunciar a si próprio!", "¡No te puedes denunciar a ti mismo!");
   static final ServerString aClass482_8781 = new ServerString("System update in: ", "System-Update in: ", "Mise à jour système dans : ", "Atualização do sistema em: ", "Actualización del sistema en: ");
   static final ServerString aClass482_8782 = new ServerString("Use", "Benutzen", "Utiliser", "Usar", "Usar");
   static final ServerString aClass482_8783 = new ServerString("You are not allowed to talk in this friends chat channel.", "Du darfst in diesem Freundes-Chatraum nicht reden.", "Vous n\'êtes pas autorisé à parler dans ce canal de discussion.", "Você não está autorizado a falar neste bate-papo entre amigos.", "No estás autorizado a hablar en este canal de chat entre amigos.");
   static final ServerString aClass482_8784 = new ServerString("You can report that person under a different rule.", "Diese Person kann bezüglich einer anderen Regel gemeldet werden.", "Vous pouvez signaler cette personne pour une autre infraction aux règles.", "Você pode denunciar essa pessoa por outro tipo de infração.", "Puedes denunciar a esa persona por otro tipo de infracción.");
   static final ServerString aClass482_8785 = new ServerString("Thank-you, your abuse report has been received.", "Vielen Dank, deine Meldung ist bei uns eingegangen.", "Merci, nous avons bien reçu votre rapport d\'abus.", "Obrigado. Sua denúncia de abuso foi recebida.", "Gracias, hemos recibido tu denuncia.");
   static final ServerString aClass482_8786 = new ServerString("Unable to add friend - system busy.", "Der Freund konnte nicht hinzugefügt werden, das System ist derzeit ausgelastet.", "Impossible d\'ajouter un ami - système occupé.", "Não foi possível adicionar o amigo. O sistema está ocupado.", "Sistema ocupado. No es posible añadir a un amigo.");
   static final ServerString aClass482_8787 = new ServerString("Invalid name", "Unzulässiger Name!", "Nom incorrect", "Nome inválido", "Nombre no válido");
   static final ServerString aClass482_8788 = new ServerString("To use this item please login to a members\' server.", "Du musst auf einer Mitglieder-Welt sein, um diesen Gegenstand zu benutzen.", "Veuillez vous connecter à un serveur d\'abonnés pour utiliser cet objet.", "Acesse um servidor para membros para usar este objeto.", "Accede a un servidor para miembros para usar este objeto.");
   static final ServerString aClass482_8789 = new ServerString("To interact with this please login to a members\' server.", "Logg dich auf einer Mitglieder-Welt ein, um damit zu interagieren.", "Veuillez vous connecter à un serveur d\'abonnés pour cette interaction.", "Para interagir, acesse um servidor para membros.", "Para interactuar, accede a un servidor para miembros.");
   static final ServerString aClass482_8790 = new ServerString("Nothing interesting happens.", "Nichts Interessantes passiert.", "Il ne se passe rien d\'intéressant.", "Nada de interessante acontece.", "No sucede nada interesante.");
   static final ServerString aClass482_8791 = new ServerString("You can\'t reach that.", "Da kommst du nicht hin.", "Vous ne pouvez pas l\'atteindre.", "Você não consegue alcançar isso.", "No puedes alcanzar eso.");
   static final ServerString aClass482_8792 = new ServerString("Invalid teleport!", "Unzulässiger Teleport!", "Téléportation non valide !", "Teleporte inválido!", "¡Teletransporte no válido!");
   public static final ServerString continueStr = new ServerString("Continue", "Weiter", "Continuer", "Continuar", "Continuar");
   public static final ServerString examineStr = new ServerString("Examine", "Untersuchen", "Examiner", "Examinar", "Examinar");
   static final ServerString aClass482_8795 = new ServerString("Unable to add friend - unknown player.", "Spieler konnte nicht hinzugefügt werden - Spieler unbekannt.", "Impossible d\'ajouter l\'ami - joueur inconnu.", "Não foi possível adicionar esse amigo - jogador desconhecido.", "Jugador desconocido. No es posible añadir a ese amigo.");
   static final ServerString aClass482_8796 = new ServerString("Unable to add name - system busy.", "Der Name konnte nicht hinzugefügt werden, das System ist derzeit ausgelastet.", "Impossible d\'ajouter un nom - système occupé.", "Não foi possível adicionar o nome. O sistema está ocupado.", "Sistema ocupado. No es posible añadir el nombre.");
   static final ServerString aClass482_8797 = new ServerString("Unable to add name - unknown player.", "Name konnte nicht hinzugefügt werden - Spieler unbekannt.", "Impossible d\'ajouter le nom - joueur inconnu.", "Não foi possível adicionar esse nome - jogador desconhecido.", "Jugador desconocido. No es posible añadir el nombre.");
   public static final ServerString aClass482_8798 = new ServerString("Your friends list is full (200 names maximum)", "Deine Freunde-Liste ist voll, du hast das Maximum von 200 erreicht.", "Votre liste d\'amis est pleine (200 noms maximum).", "Sua lista de amigos está cheia. O limite é de 200 nomes.", "Tu lista de amigos está llena. El límite es de 200 amigos.");
   public static final ServerString aClass482_8799 = new ServerString("flash3:", "blinken3:", "clignotant3:", "flash3:", "parpadeante3:");
   static final ServerString aClass482_8800 = new ServerString("Unable to delete name - system busy.", "Name konnte nicht gelöscht werden - Systemfehler.", "Impossible d\'effacer le nom - système occupé.", "Não foi possível deletar o nome - sistema ocupado.", "Sistema ocupado. No es posible borrar el nombre.");
   static final ServerString aClass482_8801 = new ServerString("Unable to send message - system busy.", "Deine Nachricht konnte nicht verschickt werden, das System ist derzeit ausgelastet.", "Impossible d\'envoyer un message - système occupé.", "Não foi possível enviar a mensagem. O sistema está ocupado.", "Sistema ocupado. No es posible enviar el mensaje.");
   static final ServerString aClass482_8802 = new ServerString("Ok", "Okay", "OK", "Ok", "OK");
   static final ServerString aClass482_8803 = new ServerString("You cannot report that person for Staff Impersonation, they are Jagex Staff.", "Diese Person ist ein Jagex-Mitarbeiter!", "Cette personne est un membre du personnel de Jagex, vous ne pouvez pas la signaler pour abus d\'identité.", "Você não pode denunciar essa pessoa por tentar se passar por um membro da equipe Jagex, pois ela faz parte da equipe.", "Esa persona es miembro del personal de Jagex, no puedes denunciarla por suplantación de identidad.");
   static final ServerString aClass482_8804 = new ServerString("Unable to send message - player not on your friends list.", "Nachricht kann nicht geschickt werden,", "Impossible d\'envoyer un message - joueur non inclus dans votre liste d\'amis.", "Não foi possível enviar a mensagem. O jogador não está na sua lista de amigos.", "No es posible enviar el mensaje. El jugador no está en tu lista de amigos.");
   static final ServerString aClass482_8805 = new ServerString((String)null, "Spieler nicht auf deiner Freunde-Liste.", (String)null, (String)null, (String)null);
   static final ServerString aClass482_8806 = new ServerString("You appear to be telling someone your password - please don\'t!", "Willst du jemandem dein Passwort verraten? Das darfst du nicht! Falls das", "Il semble que vous révéliez votre mot de passe à quelqu\'un - ne faites jamais ça !", "Parece que você está revelando sua senha a alguém. Não faça isso!", "Parece que le estás revelando a alguien tu contraseña. ¡No debes hacerlo!");
   static final ServerString aClass482_8807 = new ServerString("If you are not, please change your password to something more obscure!", "nicht der Fall ist, ändere dein Passwort zu einem ungewöhnlicheren Begriff!", "Si ce n\'est pas le cas, remplacez votre mot de passe par une formule moins évidente !", "Caso não esteja, altere sua senha para algo mais obscuro!", "¡Si no es así, cambia tu contraseña por una menos evidente!");
   static final ServerString aClass482_8808 = new ServerString("Unable to send message - set your display name first by logging into the game.", "Nachricht konnte nicht gesendet werden.  Bitte richte erst deinen Charakternamen ein, ", "Impossible d\'envoyer le message - enregistrez un nom de personnage en vous connectant au jeu.", "Não é possível enviar a mensagem. Defina um nome de personagem primeiro, fazendo login no jogo.", "No es posible enviar el mensaje. Registra primero un nombre de personaje conectándote al juego.");
   static final ServerString aClass482_8809 = new ServerString("You have been kicked from the channel.", "Du wurdest aus dem Chatraum rausgeworfen.", "Vous avez été expulsé du canal.", "Você foi expulso do canal.", "Se te ha expulsado del canal.");
   static final ServerString aClass482_8810 = new ServerString("Attempting to join channel...", "Chatraum wird betreten...", "Tentative de connexion au canal...", "Tentando acessar canal...", "Intentando acceder a un canal...");
   static final ServerString aClass482_8811 = new ServerString((String)null, "die kürzlich gesprochen oder gehandelt haben.", (String)null, (String)null, (String)null);
   static final ServerString aClass482_8812 = new ServerString("That player is offline, or has privacy mode enabled.", "Dieser Spieler ist offline oder hat den Privatsphären-Modus aktiviert.", "Ce joueur est déconnecté ou en mode privé.", "O jogador está offline ou está com o modo de privacidade ativado.", "Este jugador está desconectado o ha activado el modo de privacidad.");
   static final ServerString aClass482_8813 = new ServerString("You cannot send a quick chat message to a player on this world at this time.", "Einem Spieler auf dieser Welt können derzeit keine Direktchat-Nachrichten", "Impossible d\'envoyer un message rapide à un joueur de ce serveur à l\'heure actuelle.", "Você não pode enviar uma mensagem de papo rápido para um jogador neste mundo neste momento.", "En estos momentos no puedes enviar un mensaje rápido de chat a un jugador en este mundo.");
   public static final ServerString aClass482_8814 = new ServerString("purple:", "lila:", "violet:", "roxo:", "violeta:");
   static final ServerString aClass482_8815 = new ServerString("This player is on a quick chat world and cannot receive your message.", "Der Spieler kann auf einer Direktchat-Welt keine Nachrichten empfangen.", "Ce joueur est sur un serveur à messagerie rapide et ne peut pas recevoir votre message.", "Este jogador não pode receber sua mensagem porque está em um mundo de papo rápido.", "Este jugador no puede recibir su mensaje porque está en un mundo de chat rápido.");
   static final ServerString aClass482_8816 = new ServerString((String)null, "der Spieler ist momentan nicht verfügbar.", (String)null, (String)null, (String)null);
   static final ServerString aClass482_8817 = new ServerString("friends_chat", "friends_chat", "friends_chat", "friends_chat", "friends_chat");
   static final ServerString aClass482_8818 = new ServerString("Please wait until you are logged out of your previous channel.", "Bitte warte, bis du den vorherigen Chatraum verlassen hast.", "Veuillez attendre d\'être déconnecté(e) de votre canal précédent.", "Aguarde até se desconectar do canal anterior.", "Por favor, espera hasta haberte desconectado del anterior chat.");
   public static final ServerString errorCommandStr = new ServerString("There was an error executing the command.", "Es gab einen Fehler beim Ausführen des Befehls.", "Une erreur s\'est produite lors de l\'exécution de la commande.", "Houve um erro quando o comando foi executado.", "Se produjo un error al ejecutar el comando.");
   static final ServerString aClass482_8820 = new ServerString("Error sending message to friends chat - please try again later!", "Fehler beim Versenden der Nachricht - bitte versuch es später erneut.", "Erreur lors de l\'envoi de ce message – veuillez réessayer ultérieurement !", "Erro ao enviar mensagem para bate-papo entre amigos - tente novamente mais tarde!", "Se ha producido un error al enviar un mensaje al chat entre amigos, por favor, inténtalo más tarde.");
   static final ServerString aClass482_8821 = new ServerString("The channel you tried to join is currently full.", "Der von dir gewünschte Chatraum ist derzeit überfüllt.", "Le canal que vous essayez de rejoindre est plein.", "O canal que você tentou acessar está cheio no momento.", "El canal al que intentas unirte está lleno en estos momentos.");
   static final ServerString aClass482_8822 = new ServerString("Chat disabled", "Deaktiviert", "Messagerie désactivée", "Bate-papo desativado", "Chat desactivado");
   public static final ServerString cancelOptionStr = new ServerString("Cancel", "Abbrechen", "Annuler", "Cancelar", "Cancelar");
   static final ServerString aClass482_8824 = new ServerString("Sending request to leave channel...", "Chatraum wird verlassen...", "Envoi de la demande de sortie du canal...", "Enviando solicitação para sair do canal...", "Enviando solicitud para abandonar el canal...");
   static final ServerString aClass482_8825 = new ServerString("Already attempting to join a channel - please wait...", "Du versuchst bereits, einem Chatraum beizutreten - bitte warte.", "Tentative de connexion au canal déjà en cours - veuillez patienter...", "Já há uma tentativa de entrar em um canal. Aguarde...", "Ya estás intentando unirte a un canal. Por favor, espera...");
   static final ServerString aClass482_8826 = new ServerString("Leave request already in progress - please wait...", "Du versuchst bereits, einen Chatraum zu verlassen - bitte warte.", "Demande de sortie déjà effectuée - veuillez patienter...", "Solicitação de saída já em andamento. Aguarde...", "La salida del canal está procesándose. Por favor, espera...");
   static final ServerString aClass482_8827 = new ServerString("Invalid channel name entered!", "Ungültiger Chatraum-Name angegeben.", "Nom de canal incorrect !", "Nome de canal inválido!", "¡Nombre de canal no valido!");
   static final ServerString aClass482_8828 = new ServerString("Unable to join friends chat at this time - please try again later!", "Freundes-Chatraum kann nicht betreten werden - bitte versuch es später erneut.", "Vous ne pouvez pas rejoindre ce canal de discussion pour le moment - veuillez réessayer ultérieurement !", "Não foi possível entrar no bate-papo entre amigos - tente novamente mais tarde!", "Ahora mismo no es posible unirse al chat entre amigos. ¡Por favor, inténtalo más tarde!");
   static final ServerString aClass482_8829 = new ServerString("Now talking in friends chat channel ", "Freundes-Chatraum: ", "Vous participez actuellement au canal de discussion : ", "Falando agora no bate-papo entre amigos: ", "Hablando ahora en el chat entre amigos: ");
   static final ServerString aClass482_8830 = new ServerString("Now talking in friends chat channel of player: ", "Freundes-Chat dieses Spielers beigetreten: ", "Vous participez actuellement au canal de discussion du joueur : ", "Falando agora no bate-papo entre amigos do jogador: ", "Hablando ahora en el canal de chat entre amigos del jugador: ");
   static final ServerString aClass482_8831 = new ServerString("Error joining friends chat channel - please try again later!", "Fehler beim Betreten des Freundes-Chatraums - bitte versuch es später erneut.", "Erreur lors de la connexion au canal de discussion - veuillez réessayer ultérieurement !", "Erro ao participar do bate-papo entre amigos - tente novamente mais tarde!", "Se ha producido un error al acceder al canal de chat entre amigos. ¡Por favor, inténtalo más tarde!");
   static final ServerString aClass482_8832 = new ServerString("You are temporarily blocked from joining channels - please try again later!", "Du darfst derzeit keine Chaträume betreten - bitte versuch es später.", "Vous êtes temporairement exclu des canaux - veuillez réessayer ultérieurement.", "Você está temporariamente impedido de entrar em canais. Tente novamente mais tarde!", "De momento tienes bloqueado el acceso a los canales chat. ¡Inténtalo de nuevo más tarde!");
   static final ServerString aClass482_8833 = new ServerString("Close", "Bitte schließ die momentan geöffnete Benutzeroberfläche,", "Fermez l\'interface que vous avez ouverte avant d\'utiliser le bouton « Signaler un abus ».", "Feche a interface aberta antes de usar o recurso \"Denunciar abuso\".", "Cierra la interfaz que tienes abierta antes de usar el botón \'Denunciar abuso\'.");
   public static final ServerString dropStr = new ServerString("Drop", "Fallen lassen", "Poser", "Largar", "Dejar");
   static final ServerString aClass482_8835 = new ServerString("You do not have a high enough rank to join this friends chat channel.", "Dein Rang reicht nicht aus, um diesen Freundes-Chatraum zu betreten.", "Votre rang n\'est pas assez élevé pour rejoindre ce canal de discussion.", "Você não tem uma classificação alta o suficiente para participar deste bate-papo entre amigos.", "No tienes rango suficiente para unirte a este canal de chat entre amigos.");
   static final ServerString aClass482_8836 = new ServerString("You are temporarily banned from this friends chat channel.", "Du wurdest temporär von diesem Freundes-Chatraum gesperrt.", "Vous avez été exclu temporairement de ce canal de discussion.", "Você foi temporariamente banido deste bate-papo entre amigos.", "Tienes bloqueado temporalmente el acceso a este chat entre amigos.");
   static final ServerString aClass482_8837 = new ServerString("Loading additional fonts - ", "Lade Zusatzschriftarten - ", "Chargement de polices secondaires - ", "Carregando fontes adicionais - ", "Cargando fuentes adicionales - ");
   static final ServerString aClass482_8838 = new ServerString("Your request to refresh this user\'s temporary ban was successful.", "Die Verlängerung der temporären Sperrung dieses Spielers war erfolgreich.", "Le renouvellement d\'exclusion temporaire de ce joueur a été accepté.", "Seu pedido para reiniciar a suspensão temporária deste jogador foi bem sucedido.", "Tu petición de prolongar la suspensión temporal de este usuario ha sido aceptada.");
   static final ServerString aClass482_8839 = new ServerString(" left the channel.", " hat den Chatraum verlassen.", " a quitté le canal.", " saiu do canal.", " ha abandonado el canal.");
   static final ServerString aClass482_8840 = new ServerString(" was kicked from the channel.", " wurde aus dem Chatraum rausgeworfen.", " a été expulsé du canal.", " foi expulso do canal.", " ha sido expulsado del canal.");
   public static final ServerString loadingStr2 = new ServerString("Loading...", "Lade...", "Chargement en cours...", "Carregando...", "Cargando...");
   static final ServerString aClass482_8842 = new ServerString("You have been removed from this channel.", "Du wurdest aus dem Chatraum entfernt.", "Vous avez été supprimé de ce canal.", "Você foi retirado desse canal.", "Se te ha eliminado de este canal.");
   static final ServerString aClass482_8843 = new ServerString("You will be un-muted within 24 hours.", "Du wirst innerhalb der nächsten 24 Stunden wieder sprechen können.", "Vous aurez à nouveau accès à la messagerie instantanée dans 24 heures.", "O veto será retirado dentro de 24 horas.", "Tu veto se retirará dentro de las próximas 24 horas.");
   static final ServerString aClass482_8844 = new ServerString("Unable to send message - player unavailable.", "Deine Nachricht konnte nicht verschickt werden,", "Impossible d\'envoyer un message - joueur indisponible.", "Não foi possível enviar a mensagem. O jogador não está disponível.", "No es posible enviar el mensaje, el jugador no está disponible.");
   static final ServerString aClass482_8845 = new ServerString("Join your channel by clicking \'Join Chat\' and typing: ", "Klick auf \'Betreten\' und gib ein: ", "Pour rejoindre votre canal, cliquez sur « Participer » et entrez : ", "Para entrar no seu canal, clique em \"Acessar bate-papo\" e digite: ", "Para entrar en tu canal, haz clic sobre \'Participar\' e introduce: ");
   static final ServerString aClass482_8846 = new ServerString("Unable to send abuse report - system busy.", "Meldung konnte nicht gesendet werden - Systeme überlastet", "Impossible de signaler un abus - Erreur système", "Sistema ocupado. Não foi possível enviar sua denúncia de abuso.", "Sistema ocupado. No ha sido posible enviar tu denuncia.");
   static final ServerString aClass482_8847 = new ServerString("You do not have permission to kick users in this channel.", "Du darfst keine Benutzer aus diesem Chatraum rauswerfen.", "Vous n\'êtes pas autorisé à expulser des utilisateurs de ce canal.", "Você não tem permissão para expulsar usuários neste canal.", "No tienes autorización para expulsar a usuarios de este canal.");
   public static final ServerString aClass482_8848 = new ServerString("flash1:", "blinken1:", "clignotant1:", "flash1:", "parpadeante1:");
   static final ServerString aClass482_8849 = new ServerString("Loaded additional fonts", "Zusatzschriftarten geladen", "Polices secondaires chargées", "Fontes adicionais carregadas", "Fuentes adicionales cargadas");
   static final ServerString aClass482_8850 = new ServerString("Your request to kick/ban this user was successful.", "Der Rauswurf/die Sperrung war erfolgreich.", "Votre demande d\'exclusion de ce joueur a été acceptée.", "Seu pedido para expulsar/suspender este jogador foi bem sucedido.", "Tu petición de expulsar/suspender a este usuario ha sido aceptada.");
   public static final ServerString levelStr = new ServerString("level: ", "Stufe: ", "niveau ", "nível: ", "nivel: ");
   static final ServerString aClass482_8852 = new ServerString("You have been temporarily muted due to breaking a rule.", "Aufgrund eines Regelverstoßes wurdest du vorübergehend stumm geschaltet.", "La messagerie instantanée a été temporairement bloquée suite à une infraction.", "Você foi temporariamente vetado por ter violado uma regra.", "Se te ha vetado temporalmente por haber violado una regla.");
   static final ServerString aClass482_8853 = new ServerString("This mute will remain for a further ", "Diese Stummschaltung gilt für weitere ", "Votre accès restera bloqué encore ", "Este veto permanecerá por mais ", "Este veto permancereá activo todavía durante ");
   static final ServerString aClass482_8854 = new ServerString(" days.", " Tage.", " jours.", " dias.", " días.");
   static final ServerString aClass482_8855 = new ServerString("Loaded world list data", "Liste der Welten geladen", "Liste des serveurs chargée", "Dados da lista de mundos carregados", "Datos de la lista de mundos cargados");
   static final ServerString aClass482_8856 = new ServerString("To prevent further mutes please read the rules.", "Um eine erneute Stummschaltung zu verhindern, lies bitte die Regeln.", "Pour éviter un nouveau blocage, lisez le règlement.", "Para evitar outros vetos, leia as regras.", "Para evitar otro veto, consulta el reglamento.");
   static final ServerString aClass482_8857 = new ServerString("You have been permanently muted due to breaking a rule.", "Du wurdest permanent stumm geschaltet, da du gegen eine Regel verstoßen hast.", "L\'accès à la messagerie instantanée vous a définitivement été retiré suite à une infraction.", "Você foi permanentemente vetado por ter violado uma regra.", "Se te ha vetado permanentemente por haber violado una regla.");
   public static final ServerString loadingStr = new ServerString("Loading - please wait.", "Ladevorgang - bitte warte.", "Chargement en cours. Veuillez patienter.", "Carregando. Aguarde.", "Cargando. Por favor, espera.");
   public static final ServerString profilingStr = new ServerString("Profiling...", "Profiling...", "Profilage...", "Profiling...", "Profiling...");
   public static final ServerString aClass482_8860 = new ServerString("glow3:", "leuchten3:", "brillant3:", "brilho3:", "brillante3:");
   public static final ServerString aClass482_8861 = new ServerString("Please wait - attempting to reestablish.", "Bitte warte - es wird versucht, die Verbindung wiederherzustellen.", "Veuillez patienter - tentative de rétablissement.", "Tentando reestabelecer conexão. Aguarde.", "Estamos intentando restablecer la conexión. Por favor, espera.");
   public static final ServerString checkForUpdatesStr = new ServerString("Checking for updates - ", "Suche nach Updates - ", "Vérification des mises à jour - ", "Verificando atualizações - ", "Buscando actualizaciones - ");
   public static final ServerString fetchUpdatesStr = new ServerString("Fetching Updates - ", "Lade Update - ", "Chargement des MAJ - ", "Carregando atualizações - ", "Cargando actualizaciones - ");
   static final ServerString aClass482_8864 = new ServerString("Loading config - ", "Lade Konfiguration - ", "Chargement des fichiers config - ", "Carregando config - ", "Cargando configuración - ");
   static final ServerString aClass482_8865 = new ServerString("Loaded config", "Konfig geladen.", "Fichiers config chargés", "Config carregada", "Configuración cargada");
   static final ServerString aClass482_8866 = new ServerString("Loading sprites - ", "Lade Sprites - ", "Chargement des sprites - ", "Carregando sprites - ", "Cargando sprites - ");
   static final ServerString aClass482_8867 = new ServerString("Loaded sprites", "Sprites geladen.", "Sprites chargés", "Sprites carregados", "Sprites cargados");
   static final ServerString aClass482_8868 = new ServerString("Loading wordpack - ", "Lade Wordpack - ", "Chargement du module texte - ", "Carregando pacote de palavras - ", "Cargando el módulo de texto - ");
   static final ServerString aClass482_8869 = new ServerString("Loaded wordpack", "Wordpack geladen.", "Module texte chargé", "Pacote de palavras carregado", "Módulo de texto cargado");
   static final ServerString aClass482_8870 = new ServerString("Loading interfaces - ", "Lade Benutzeroberfläche - ", "Chargement des interfaces - ", "Carregando interfaces - ", "Cargando interfaces - ");
   static final ServerString aClass482_8871 = new ServerString("Loaded interfaces", "Benutzeroberfläche geladen.", "Interfaces chargées", "Interfaces carregadas", "Interfaces cargadas");
   static final ServerString aClass482_8872 = new ServerString("Loading interface scripts - ", "Lade Interface-Skripte - ", "Chargement des interfaces - ", "Carregando scripts de interface - ", "Cargando guión de interfaz - ");
   static final ServerString aClass482_8873 = new ServerString("Loaded interface scripts", "Interface-Skripte geladen", "Interfaces chargées", "Script de interface carregados", "Guiones de interfaz cargados");
   public static final ServerString skillStr = new ServerString("skill: ", "Fertigkeit: ", "compétence ", "habilidade: ", "habilidad: ");
   public static final ServerString moreOptionsStr = new ServerString(" more options", " weitere Optionen", " autres options", " mais opções", " más opciones");
   static final ServerString aClass482_8876 = new ServerString("That user is not in this channel.", "Dieser Benutzer befindet sich nicht in diesem Chatraum.", "Cet utilisateur n\'est pas dans ce canal.", "Esse usuário não está no canal.", "Ese usuario no está en este canal.");
   public static final ServerString unableToFindStr = new ServerString("Unable to find ", "Spieler kann nicht gefunden werden: ", "Impossible de trouver ", "Não foi possível encontrar ", "No es posible encontrar a ");
   static final ServerString aClass482_8878 = new ServerString("Loading world list data", "Lade Liste der Welten", "Chargement de la liste des serveurs", "Carregando dados da lista de mundos", "Cargando datos de la lista de mundos");
   public static final ServerString aClass482_8879 = new ServerString("Your ignore list is full. Max of 100 users.", "Deine Ignorieren-Liste ist voll, du kannst nur 100 Spieler darauf eintragen.", "Votre liste noire est pleine (100 noms maximum).", "Sua lista de ignorados está cheia. O limite é de 100 usuários.", "Tu lista de jugadores ignorados está llena, el límite es de 100.");
   static final ServerString aClass482_8880 = new ServerString("Loaded client variable data", "Client-Variablen geladen", "Variables du client chargées", "As variáveis do sistema foram carregadas", "Variables de cliente cargadas");
   public static final ServerString takeStr = new ServerString("Take", "Nehmen", "Prendre", "Pegar", "Agarrar");
   static final ServerString aClass482_8882 = new ServerString("Please close the interface you have open before using \'Report Abuse\'.", "Bitte schließ die momentan geöffnete Benutzeroberfläche,", "Fermez l\'interface que vous avez ouverte avant d\'utiliser le bouton « Signaler un abus ».", "Feche a interface aberta antes de usar o recurso \"Denunciar abuso\".", "Cierra la interfaz que tienes abierta antes de usar el botón \'Denunciar abuso\'.");
   static final ServerString aClass482_8883 = new ServerString((String)null, "bevor du die Option \'Regelverstoß melden\' benutzt.", (String)null, (String)null, (String)null);
   static final ServerString aClass482_8884 = new ServerString("You are not allowed to join this user\'s friends chat channel.", "Du darfst den Freundes-Chatraum dieses Benutzers nicht betreten.", "Vous n\'êtes pas autorisé à rejoindre le canal de discussion de cet utilisateur.", "Você não pode entrar nesse bate-papo entre amigos deste usuário.", "No tienes permiso para acceder al canal de chat entre amigos de este usuario.");
   public static final ServerString aClass482_8885 = new ServerString(" from your friends list first.", " zuerst von deiner Freunde-Liste!", " de votre liste d\'amis.", " da sua lista de amigos primeiro.", " de tu lista de amigos.");
   public static final ServerString aClass482_8886 = new ServerString(" has logged out.", " loggt sich aus.", " s\'est déconnecté.", " saiu do jogo.", " se ha desconectado.");
   public static final ServerString aClass482_8887 = new ServerString("Discard", "Ablegen", "Jeter", "Descartar", "Descartar");
   static final ServerString aClass482_8888 = new ServerString("You do not have permission to kick this user.", "Du darfst diesen Benutzer nicht rauswerfen.", "Vous n\'êtes pas autorisé à expulser cet utilisateur.", "Você não tem permissão para expulsar este usuário.", "No tienes autorización para expulsar a este usuario.");
   static final ServerString aClass482_8889 = new ServerString("You have left the channel.", "Du hast den Chatraum verlassen.", "Vous avez quitté le canal.", "Você saiu do canal.", "Has salido del canal.");
   public static final ServerString attackStr = new ServerString("Attack", "Angreifen", "Attaquer", "Atacar", "Atacar");
   public static final ServerString chooseOptionStr = new ServerString("Choose Option", "Wähl eine Option", "Choisir une option", "Selecionar opção", "Seleccionar opción");
   public static final ServerString alreadyOnFriendsListStr = new ServerString(" is already on your friends list.", " steht bereits auf deiner Freunde-Liste!", " est déjà dans votre liste d\'amis.", " já está na sua lista de amigos.", " ya está en tu lista de amigos.");
   public static final ServerString walkHereStr = new ServerString("Walk here", "Hierhin gehen", "Atteindre", "Caminhar para cá", "Venir acá");
   public static final ServerString faceHereStr = new ServerString("Face here", "Hierhin drehen", "Regarder dans cette direction", "Virar para cá", "Girar hacia acá");
   public static final ServerString devConsoleStr = new ServerString("This is the developer console. To close, press the `, ² or § keys on your keyboard.", "Das ist die Entwicklerkonsole. Zum Schließen, die Tasten `, ² oder § drücken.", "Ceci est la console de développement. Pour la fermer, appuyez sur les touches `, ² ou §.", "Este é o painel de controle do desenvolvedor. Para fechar, pressione `, ² ou §.", "Esta es la consola de desarrolador. Para cerrarla, pulsa las teclas `, ² or § en tu teclado.");
   static final ServerString aClass482_8896 = new ServerString("Loaded world map", "Weltkarte geladen", "Mappemonde chargée", "Mapa-múndi carregado", "Mapamundi cargado");
   public static final ServerString ratingStr = new ServerString("rating: ", "Kampfstufe: ", "classement ", "qualificação: ", "clasificación: ");
   public static final ServerString pleaseWaitStr = new ServerString("Please wait...", "Bitte warte...", "Veuillez attendre", "Aguarde...", "Por favor, espera...");
   static final ServerString aClass482_8899 = new ServerString("The channel you tried to join does not exist.", "Der von dir gewünschte Chatraum existiert nicht.", "Le canal que vous essayez de rejoindre n\'existe pas.", "O canal que você tentou acessar não existe.", "El canal al que intentas unirte no existe.");
   public static final ServerString spacingStr = new ServerString(" ", ": ", " ", " ", " ");
   static final ServerString aClass482_8901 = new ServerString("Your friends chat channel has now been enabled!", "Dein Freundes-Chat ist jetzt eingeschaltet.", "Votre canal de discussion est maintenant activé !", "O seu bate-papo entre amigos foi ativado!", "¡Tu canal de chat entre amigos está activado!");
   public static final ServerString aClass482_8902 = new ServerString("M", "M", "M", "M", "M");
   public static final ServerString aClass482_8903 = new ServerString("K", "T", "K", "K", "K");
   public static final ServerString aClass482_8904 = new ServerString("K", "T", "K", "K", "K");
   static final ServerString aClass482_8905 = new ServerString("From", "Von:", "De", "De", "De");
   static final ServerString aClass482_8906 = new ServerString("Unable to delete friend - system busy.", "Der Freund konnte nicht entfernt werden, das System ist derzeit ausgelastet.", "Impossible de supprimer un ami - système occupé.", "Não foi possível excluir o amigo. O sistema está ocupado.", "Servidor ocupado. No es posible borrar al amigo.");
   static final ServerString aClass482_8907 = new ServerString("You have sent too many abuse reports today! Do not abuse this system!", "Du hast heute schon zu viele Regelverstöße gemeldet! Missbrauch das System nicht!", "Vous avez signalé trop d’abus pour aujourd’hui. N’abusez pas de ce système !", "Você já denunciou abuso muitas vezes hoje. Não abuse do sistema!", "¡Ya has denunciado demasiadas infracciones hoy! ¡No abuses del sistema!");
   public static final ServerString aClass482_8908 = new ServerString(" has logged in.", " loggt sich ein.", " s\'est connecté.", " entrou no jogo.", " se ha conectado.");
   public static final ServerString aClass482_8909 = new ServerString(" is already on your ignore list.", " steht bereits auf deiner Ignorieren-Liste!", " est déjà dans votre liste noire.", " já está na sua lista de ignorados.", " ya está en tu lista de ignorados.");
   public static final ServerString aClass482_8910 = new ServerString("You can\'t add yourself to your own friends list.", "Du kannst dich nicht auf deine eigene Freunde-Liste setzen!", "Vous ne pouvez pas ajouter votre nom à votre liste d\'amis.", "Você não pode adicionar a si próprio à sua lista de amigos.", "No puedes añadirte a tu propia lista de amigos.");
   public static final ServerString aClass482_8911 = new ServerString("You can\'t add yourself to your own ignore list.", "Du kannst dich nicht auf deine eigene Ignorieren-Liste setzen!", "Vous ne pouvez pas ajouter votre nom à votre liste noire.", "Você não pode adicionar a si próprio à sua lista de ignorados.", "No puedes añadirte a tu propia lista de ignorados.");
   static final ServerString aClass482_8912 = new ServerString("Changes will take effect on your friends chat in the next 60 seconds.", "Die Änderungen am Freundes-Chat werden innerhalb von 60 Sekunden übernommen.", "Les modifications seront apportés à votre canal de discussion dans les 60 prochaines secondes.", "As mudanças acontecerão em seu bate-papo entre amigos nos próximos 60 segundos.", "Los cambios en tu chat de amigos se realizarán en los próximos 60 segundos.");
   public static final ServerString pleaseRemoveStr = new ServerString("Please remove ", "Bitte entferne ", "Veuillez commencer par supprimer ", "Remova ", "Elimina primero a ");
   public static final ServerString fromIgnoreListStr = new ServerString(" from your ignore list first.", " zuerst von deiner Ignorieren-Liste!", " de votre liste noire.", " da sua lista de ignorados primeiro.", " de tu lista de ignorados.");
   public static final ServerString aClass482_8915 = new ServerString("Please remove ", "Bitte entferne ", "Veuillez commencer par supprimer ", "Remova ", "Elimina primero a ");
   static final ServerString aClass482_8916 = new ServerString("To go here you must login to a members\' server.", "Du musst auf einer Mitglieder-Welt sein, um dort hinzukommen.", "Vous devez vous connecter à un serveur d\'abonnés pour aller à cet endroit.", "Para entrar aqui, acesse um servidor para membros.", "Para entrar aquí, debes acceder a un servidor para miembros.");
   public static final ServerString aClass482_8917 = new ServerString("yellow:", "gelb:", "jaune:", "amarelo:", "amarillo:");
   public static final ServerString aClass482_8918 = new ServerString("red:", "rot:", "rouge:", "vermelho:", "rojo:");
   public static final ServerString aClass482_8919 = new ServerString("green:", "grün:", "vert:", "verde:", "verde:");
   public static final ServerString aClass482_8920 = new ServerString("cyan:", "blaugrün:", "cyan:", "ciano:", "cian:");
   static final ServerString aClass482_8921 = new ServerString(" joined the channel.", " hat den Chatraum betreten.", " a rejoint le canal.", " entrou no canal.", " se ha unido al canal.");
   public static final ServerString connLostStr = new ServerString("Connection lost.", "Verbindung abgebrochen.", "Connexion perdue.", "Conexão perdida.", "Conexión perdida.");
   static final ServerString aClass482_8923 = new ServerString("For that rule you can only report players who have spoken or traded recently.", "Mit dieser Option können nur Spieler gemeldet werden,", "Cette règle n\'est invocable que pour les discussions ou échanges récents.", "Para essa regra, você só pode denunciar jogadores com quem tenha falado ou negociado recentemente.", "Sólo puedes denunciar por esa regla a jugadores que hayan hablado o comerciado recientemente.");
   public static final ServerString aClass482_8924 = new ServerString("flash2:", "blinken2:", "clignotant2:", "flash2:", "parpadeante2:");
   public static final ServerString aClass482_8925 = new ServerString("M", "M", "M", "M", "M");
   public static final ServerString aClass482_8926 = new ServerString("glow1:", "leuchten1:", "brillant1:", "brilho1:", "brillante1:");
   public static final ServerString aClass482_8927 = new ServerString("glow2:", "leuchten2:", "brillant2:", "brilho2:", "brillante2:");
   static final ServerString aClass482_8928 = new ServerString("You can spot a Jagex moderator by the gold crown next to their name.", "Jagex-Mitarbeiter haben eine goldene Krone neben ihrem Namen.", "Vous pouvez reconnaître les modérateurs Jagex à la couronne dorée en regard de leur nom.", "Os moderadores da Jagex são identificados por uma coroa dourada ao lado de seu nome.", "Los moderadores de Jagex tienen una corona dorada a un lado del nombre.");
   static final ServerString aClass482_8929 = new ServerString("Loading world map - ", "Lade Weltkarte - ", "Chargement de la mappemonde - ", "Carregando mapa-múndi - ", "Cargando mapamundi - ");
   public static final ServerString aClass482_8930 = new ServerString("wave2:", "welle2:", "ondulation2:", "onda2:", "onda2:");
   public static final ServerString aClass482_8931 = new ServerString("shake:", "schütteln:", "tremblement:", "tremor:", "temblor:");
   public static final ServerString aClass482_8932 = new ServerString("scroll:", "scrollen:", "déroulement:", "rolagem:", "desplazar:");
   public static final ServerString aClass482_8933 = new ServerString("slide:", "gleiten:", "glissement:", "deslizamento:", "deslizar:");
   static final ServerString aClass482_8934 = new ServerString("Friend", "Freund", "Ami", "Amigo", "Amigo");
   final Map languageMap = new HashMap(7);


   public String getText(LanguagePack var1, int var2) {
      return (String)this.languageMap.get(var1);
   }

   ServerString(String var1, String var2, String var3, String var4, String var5) {
      this.languageMap.put(LanguagePack.aClass526_9276, var1);
      this.languageMap.put(LanguagePack.aClass526_9277, var2);
      this.languageMap.put(LanguagePack.aClass526_9278, var3);
      this.languageMap.put(LanguagePack.aClass526_9281, var4);
      this.languageMap.put(LanguagePack.aClass526_9282, var5);
   }

   static final void method5711(RSInterfaceData var0, int var1) {
      String var2;
      if(null != Class521.myPlayer && Class521.myPlayer.aString_1467 != null) {
         var2 = Class521.myPlayer.method997(false, 581581839);
      } else {
         var2 = "";
      }

      var0.stringData[(var0.stringDataIndex += -1828074049) * 863838783 - 1] = var2;
   }

   static final void method5712(RSInterfaceData var0, int var1) throws Exception_Sub1 {
      var0.intTypeIndex -= 1462854468;
      int var2 = var0.intTypes[var0.intTypeIndex * -831324111];
      int var3 = var0.intTypes[1 + -831324111 * var0.intTypeIndex];
      int var4 = var0.intTypes[-831324111 * var0.intTypeIndex + 2];
      GameCoord var5 = GameCoord.createCoord((float)var2, (float)var3, (float)var4);
      Class542.aClass43_Sub1_9475.method358(var5, -1652523658);
      var5.store();
   }

   static final void method5713(RSInterfaceData var0, int var1) {
      var0.intTypes[(var0.intTypeIndex += -708028207) * -831324111 - 1] = 7308247 * Class109.anInt_2044;
   }

   static final void method5714(RSInterfaceData var0, int var1) {
      Class552 var2 = var0.aBoolean_9522?var0.aClass552_9506:var0.aClass552_9492;
      RSInterface var3 = var2.aClass132_9524;
      RSInterfaceGroup var4 = var2.aClass112_9523;
      Class540_Sub32.method4391(var3, var4, var0, 2027280423);
   }
}
